"""edit model Service

Revision ID: 957aa17785c0
Revises: 330209e5532c
Create Date: 2025-05-25 11:59:42.578363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957aa17785c0'
down_revision: Union[str, None] = '330209e5532c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('service', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('service', sa.Column('button_text', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'button_text')
    op.drop_column('service', 'color')
    op.drop_column('service', 'progress')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
